import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My resturant app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/products">My Resturant</Link>
        </h1>

        <p className={styles.description}>
          Get started by clicking the link above{' '}
          <code className={styles.code}>My Resturant</code>
        </p>

        </main>
        </div>
  )
}
